name: EVN Scraper Daily

on:
  workflow_dispatch: # Cho phép nhấn nút chạy bằng tay
  schedule:
    - cron: '0 0 * * *' # Tự động chạy vào 7h sáng hàng ngày (giờ VN)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: python main.py

      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: evn-result
          path: datasauget.xlsx
